### ISSUE TITLE
With missing kerberos: local variable 'h' referenced before assignment

### ISSUE THREAD

**Issue by lukaszachy** [psss/python-nitrate#11]
When I am using Kerberos to authenticate but I am missing ticket this misleading exception occurs:
```python
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nitrate/base.py", line 200, in _server
    Config().nitrate.username,
AttributeError: 'Section' object has no attribute 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nitrate/xmlrpc_driver.py", line 105, in single_request_with_cookies
    h = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1267, in send_request
    connection = self.make_connection(host)
  File "/usr/lib/python3.7/site-packages/nitrate/xmlrpc_driver.py", line 185, in make_connection
    chost, self._extra_headers, x509 = self.get_host_info(host)
  File "/usr/lib/python3.7/site-packages/nitrate/xmlrpc_driver.py", line 163, in get_host_info
    response = vc.step()
  File "<decorator-gen-15>", line 2, in step
  File "/usr/lib64/python3.7/site-packages/gssapi/_utils.py", line 167, in check_last_err
    return func(self, *args, **kwargs)
  File "<decorator-gen-5>", line 2, in step
  File "/usr/lib64/python3.7/site-packages/gssapi/_utils.py", line 127, in catch_and_return_token
    return func(self, *args, **kwargs)
  File "/usr/lib64/python3.7/site-packages/gssapi/sec_contexts.py", line 521, in step
    return self._initiator_step(token=token)
  File "/usr/lib64/python3.7/site-packages/gssapi/sec_contexts.py", line 542, in _initiator_step
    token)
  File "gssapi/raw/sec_contexts.pyx", line 244, in gssapi.raw.sec_contexts.init_sec_context
gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529639053): No Kerberos credentials available (default cache: KCM:)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/nitrate/base.py", line 206, in _server
    Config().nitrate.url).server
  File "/usr/lib/python3.7/site-packages/nitrate/xmlrpc_driver.py", line 443, in __init__
    login_dict = self.do_command("Auth.login_krbv", [])
  File "/usr/lib/python3.7/site-packages/nitrate/xmlrpc_driver.py", line 393, in do_command
    return getattr(self.server, verb)(*params)
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.7/site-packages/nitrate/xmlrpc_driver.py", line 137, in single_request_with_cookies
    h.close()
UnboundLocalError: local variable 'h' referenced before assignment
```

Easy way to reproduce (klist is empty)
```python
import nitrate
nitrate.User()._server.User.get_me()
```

**Comment by psss** [comment]
Yes, we should give a nice error for such cases. Not a regression though:

    gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS
    failure.  Minor code may provide more information, Minor
    (2529638919): Server HTTP/example.com@REDHAT.COM not found in
    Kerberos database

@ZelenyMartin, would you like to have a look at this?

**Comment by lukaszachy** [comment]
I beg to differ. There used to be ```gssapi.raw.misc.GSSError```. Now ```UnboundLocalError```` is raised, which, I believe, is more serious as it is code flow error as opposed to 'you don't have permissions'

**Comment by lukaszachy** [comment]
Please leave this issue for Dita,  you can expect PR tomorrow-ish :) Thanks.

**Comment by psss** [comment]
Fixed by merging #15.

**Comment by lukaszachy** [comment]
@psss @ZelenyMartin Any plans to make a release and get the fix into Fedora/EPEL?

**Comment by psss** [comment]
@ZelenyMartin, if you want we can take this as an opportunity to enable you building the package for Fedora.
