### ISSUE TITLE
Traceback when importing from immutable with python2

### ISSUE THREAD

**Issue by martinky82** [psss/python-nitrate#12]
Traceback (most recent call last):
  File "./tcms-sort", line 5, in <module>
    import nitrate
  File "/usr/lib/python2.7/site-packages/nitrate/__init__.py", line 67, in <module>
    from nitrate.base import Nitrate
  File "/usr/lib/python2.7/site-packages/nitrate/nitrate/__init__.py", line 67, in <module>
    from nitrate.base import Nitrate
  File "/usr/lib/python2.7/site-packages/nitrate/base.py", line 426, in <module>
    from nitrate.cache import Cache
  File "/usr/lib/python2.7/site-packages/nitrate/nitrate/cache.py", line 121, in <module>
    import nitrate.immutable as immutable
  File "/usr/lib/python2.7/site-packages/nitrate/immutable.py", line 32, in <module>
    from nitrate.base import Nitrate, NitrateNone, _getter, _idify
  File "/usr/lib/python2.7/site-packages/nitrate/nitrate/base.py", line 426, in <module>
    from nitrate.cache import Cache
  File "/usr/lib/python2.7/site-packages/nitrate/cache.py", line 121, in <module>
    import nitrate.immutable as immutable
  File "/usr/lib/python2.7/site-packages/nitrate/nitrate/immutable.py", line 1341, in <module>
    from nitrate.mutable import TestCase, CaseRun
  File "/usr/lib/python2.7/site-packages/nitrate/mutable.py", line 1473, in <module>
    from nitrate.containers import (CaseBugs, CaseComponents, CasePlans,
  File "/usr/lib/python2.7/site-packages/nitrate/nitrate/containers.py", line 71, in <module>
    from nitrate.immutable import Component, Bug, Tag
ImportError: cannot import name Component

**Comment by martinky82** [comment]
It turned out the issue was probably caused by leftovers from previous python-nitrate versions in site-packages. Removing them solved it.
